# Taken from https://github.com/github-packages-examples/ghcr-publish/blob/master/.github/workflows/publish.yml
name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish image
        run: docker push ${{ env.IMAGE }}
